Installer les differents  bibliotheques

In [1]:
!pip install nltk

Requirement already satisfied: nltk in c:\users\pc\anaconda3\lib\site-packages (3.6.1)
Requirement already satisfied: click in c:\users\pc\anaconda3\lib\site-packages (from nltk) (7.1.2)
Requirement already satisfied: regex in c:\users\pc\anaconda3\lib\site-packages (from nltk) (2021.4.4)
Requirement already satisfied: tqdm in c:\users\pc\anaconda3\lib\site-packages (from nltk) (4.59.0)
Requirement already satisfied: joblib in c:\users\pc\anaconda3\lib\site-packages (from nltk) (1.0.1)

In [24]:
rawData = open("C:\\Users\\PC\\Desktop\\Cours_INGC3\\NLP\\SMSSpamCollection.tsv").read()
rawData[0:250]

"ham\tI've been searching for the right words to thank you for this breather. I promise i wont take your help for granted and will fulfil my promise. You have been wonderful and a blessing at all times.\nspam\tFree entry in 2 a wkly comp to win FA Cup fi"

In [25]:
import warnings
warnings.filterwarnings('ignore')

In [26]:
#Lire le fichier  SMSSpamCollection.tsv par la methode pandas
import pandas as pd
data = pd.read_csv("C:\\Users\\PC\\Desktop\\Cours_INGC3\\NLP\\SMSSpamCollection.tsv", sep ="\t",
                  names = ['label', 'body_text'], header = None)

In [27]:
#Afficher les 5 premieres ligne du fichier
data.head()

  label                                          body_text
0   ham  I've been searching for the right words to tha...
1  spam  Free entry in 2 a wkly comp to win FA Cup fina...
2   ham  Nah I don't think he goes to usf, he lives aro...
3   ham  Even my brother is not like to speak with me. ...
4   ham                I HAVE A DATE ON SUNDAY WITH WILL!!

In [28]:
#Importer toutes les ponctuation dans l e bibliotheque string
import string
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [29]:
#Supprimer les ponctuation dans le texte
def remove_punct(text): 
    text_no_punct = ''.join([char  for char in text if char not in string.punctuation])
    return text_no_punct
data['body_text_no_punct'] = data['body_text'].apply(lambda x: remove_punct(x))
data.head()

,label,body_text,body_text_no_punct
0,ham,I've been searching for the right words to tha...,Ive been searching for the right words to than...
1,spam,Free entry in 2 a wkly comp to win FA Cup fina...,Free entry in 2 a wkly comp to win FA Cup fina...
2,ham,"Nah I don't think he goes to usf, he lives aro...",Nah I dont think he goes to usf he lives aroun...
3,ham,Even my brother is not like to speak with me. ...,Even my brother is not like to speak with me T...
4,ham,I HAVE A DATE ON SUNDAY WITH WILL!!,I HAVE A DATE ON SUNDAY WITH WILL

In [30]:
import  re 
def tokenizer(text):
    tokens = re.split('\W+', text)
    return  tokens
data['body_text_tokenized'] = data['body_text_no_punct'].apply(lambda x: tokenizer(x))
data.head()

,label,body_text,body_text_no_punct,body_text_tokenized
0,ham,I've been searching for the right words to tha...,Ive been searching for the right words to than...,"[Ive, been, searching, for, the, right, words,..."
1,spam,Free entry in 2 a wkly comp to win FA Cup fina...,Free entry in 2 a wkly comp to win FA Cup fina...,"[Free, entry, in, 2, a, wkly, comp, to, win, F..."
2,ham,"Nah I don't think he goes to usf, he lives aro...",Nah I dont think he goes to usf he lives aroun...,"[Nah, I, dont, think, he, goes, to, usf, he, l..."
3,ham,Even my brother is not like to speak with me. ...,Even my brother is not like to speak with me T...,"[Even, my, brother, is, not, like, to, speak, ..."
4,ham,I HAVE A DATE ON SUNDAY WITH WILL!!,I HAVE A DATE ON SUNDAY WITH WILL,"[I, HAVE, A, DATE, ON, SUNDAY, WITH, WILL]"

In [31]:
#importer le nltk puis faire telechargement 
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\PC\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [32]:
stopwords = nltk.corpus.stopwords.words('english')

In [33]:
def remove_stopwords(tokenized_list):
    text_no_stop = [ word for word in tokenized_list if word not in stopwords]
    return text_no_stop
data['body_text_nostop'] = data['body_text_tokenized'].apply(lambda x: remove_stopwords(x))
data.head()

,label,body_text,body_text_no_punct,body_text_tokenized,body_text_nostop
0,ham,I've been searching for the right words to tha...,Ive been searching for the right words to than...,"[Ive, been, searching, for, the, right, words,...","[Ive, searching, right, words, thank, breather..."
1,spam,Free entry in 2 a wkly comp to win FA Cup fina...,Free entry in 2 a wkly comp to win FA Cup fina...,"[Free, entry, in, 2, a, wkly, comp, to, win, F...","[Free, entry, 2, wkly, comp, win, FA, Cup, fin..."
2,ham,"Nah I don't think he goes to usf, he lives aro...",Nah I dont think he goes to usf he lives aroun...,"[Nah, I, dont, think, he, goes, to, usf, he, l...","[Nah, I, dont, think, goes, usf, lives, around..."
3,ham,Even my brother is not like to speak with me. ...,Even my brother is not like to speak with me T...,"[Even, my, brother, is, not, like, to, speak, ...","[Even, brother, like, speak, They, treat, like..."
4,ham,I HAVE A DATE ON SUNDAY WITH WILL!!,I HAVE A DATE ON SUNDAY WITH WILL,"[I, HAVE, A, DATE, ON, SUNDAY, WITH, WILL]","[I, HAVE, A, DATE, ON, SUNDAY, WITH, WILL]"

In [34]:
ps = nltk.PorterStemmer()
def stemming(tokenized_text):
    text = [ps.stem(word) for  word in tokenized_text]
    return text
data['body_te xt_stemmed'] = data['body_text_nostop'].apply(lambda x: stemming(x))
data.head(10)

,label,body_text,body_text_no_punct,body_text_tokenized,body_text_nostop,body_te xt_stemmed
0,ham,I've been searching for the right words to tha...,Ive been searching for the right words to than...,"[Ive, been, searching, for, the, right, words,...","[Ive, searching, right, words, thank, breather...","[ive, search, right, word, thank, breather, i,..."
1,spam,Free entry in 2 a wkly comp to win FA Cup fina...,Free entry in 2 a wkly comp to win FA Cup fina...,"[Free, entry, in, 2, a, wkly, comp, to, win, F...","[Free, entry, 2, wkly, comp, win, FA, Cup, fin...","[free, entri, 2, wkli, comp, win, fa, cup, fin..."
2,ham,"Nah I don't think he goes to usf, he lives aro...",Nah I dont think he goes to usf he lives aroun...,"[Nah, I, dont, think, he, goes, to, usf, he, l...","[Nah, I, dont, think, goes, usf, lives, around...","[nah, i, dont, think, goe, usf, live, around, ..."
3,ham,Even my brother is not like to speak with me. ...,Even my brother is not like to speak with me T...,"[Even, my, brother, is, not, like, to, speak, ...","[Even, brother, like, speak, They, treat, like...","[even, brother, like, speak, they, treat, like..."
4,ham,I HAVE A DATE ON SUNDAY WITH WILL!!,I HAVE A DATE ON SUNDAY WITH WILL,"[I, HAVE, A, DATE, ON, SUNDAY, WITH, WILL]","[I, HAVE, A, DATE, ON, SUNDAY, WITH, WILL]","[i, have, a, date, on, sunday, with, will]"
5,ham,As per your request 'Melle Melle (Oru Minnamin...,As per your request Melle Melle Oru Minnaminun...,"[As, per, your, request, Melle, Melle, Oru, Mi...","[As, per, request, Melle, Melle, Oru, Minnamin...","[as, per, request, mell, mell, oru, minnaminun..."
6,spam,WINNER!! As a valued network customer you have...,WINNER As a valued network customer you have b...,"[WINNER, As, a, valued, network, customer, you...","[WINNER, As, valued, network, customer, select...","[winner, as, valu, network, custom, select, re..."
7,spam,Had your mobile 11 months or more? U R entitle...,Had your mobile 11 months or more U R entitled...,"[Had, your, mobile, 11, months, or, more, U, R...","[Had, mobile, 11, months, U, R, entitled, Upda...","[had, mobil, 11, month, u, r, entitl, updat, l..."
8,ham,I'm gonna be home soon and i don't want to tal...,Im gonna be home soon and i dont want to talk ...,"[Im, gonna, be, home, soon, and, i, dont, want...","[Im, gonna, home, soon, dont, want, talk, stuf...","[im, gonna, home, soon, dont, want, talk, stuf..."
9,spam,"SIX chances to win CASH! From 100 to 20,000 po...",SIX chances to win CASH From 100 to 20000 poun...,"[SIX, chances, to, win, CASH, From, 100, to, 2...","[SIX, chances, win, CASH, From, 100, 20000, po...","[six, chanc, win, cash, from, 100, 20000, poun..."

In [35]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\PC\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [36]:
 nltk.download('omw-1.4')

[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\PC\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

True

In [37]:
wn = nltk.WordNetLemmatizer()
def lemmatize(tokenized_text):
    text = [wn.lemmatize(word) for word in tokenized_text]
    return text

data[ 'body_text_lemmaized'] = data['body_text_nostop'].apply(lambda x: lemmatize(x))
data.head(10)

,label,body_text,body_text_no_punct,body_text_tokenized,body_text_nostop,body_te xt_stemmed,body_text_lemmaized
0,ham,I've been searching for the right words to tha...,Ive been searching for the right words to than...,"[Ive, been, searching, for, the, right, words,...","[Ive, searching, right, words, thank, breather...","[ive, search, right, word, thank, breather, i,...","[Ive, searching, right, word, thank, breather,..."
1,spam,Free entry in 2 a wkly comp to win FA Cup fina...,Free entry in 2 a wkly comp to win FA Cup fina...,"[Free, entry, in, 2, a, wkly, comp, to, win, F...","[Free, entry, 2, wkly, comp, win, FA, Cup, fin...","[free, entri, 2, wkli, comp, win, fa, cup, fin...","[Free, entry, 2, wkly, comp, win, FA, Cup, fin..."
2,ham,"Nah I don't think he goes to usf, he lives aro...",Nah I dont think he goes to usf he lives aroun...,"[Nah, I, dont, think, he, goes, to, usf, he, l...","[Nah, I, dont, think, goes, usf, lives, around...","[nah, i, dont, think, goe, usf, live, around, ...","[Nah, I, dont, think, go, usf, life, around, t..."
3,ham,Even my brother is not like to speak with me. ...,Even my brother is not like to speak with me T...,"[Even, my, brother, is, not, like, to, speak, ...","[Even, brother, like, speak, They, treat, like...","[even, brother, like, speak, they, treat, like...","[Even, brother, like, speak, They, treat, like..."
4,ham,I HAVE A DATE ON SUNDAY WITH WILL!!,I HAVE A DATE ON SUNDAY WITH WILL,"[I, HAVE, A, DATE, ON, SUNDAY, WITH, WILL]","[I, HAVE, A, DATE, ON, SUNDAY, WITH, WILL]","[i, have, a, date, on, sunday, with, will]","[I, HAVE, A, DATE, ON, SUNDAY, WITH, WILL]"
5,ham,As per your request 'Melle Melle (Oru Minnamin...,As per your request Melle Melle Oru Minnaminun...,"[As, per, your, request, Melle, Melle, Oru, Mi...","[As, per, request, Melle, Melle, Oru, Minnamin...","[as, per, request, mell, mell, oru, minnaminun...","[As, per, request, Melle, Melle, Oru, Minnamin..."
6,spam,WINNER!! As a valued network customer you have...,WINNER As a valued network customer you have b...,"[WINNER, As, a, valued, network, customer, you...","[WINNER, As, valued, network, customer, select...","[winner, as, valu, network, custom, select, re...","[WINNER, As, valued, network, customer, select..."
7,spam,Had your mobile 11 months or more? U R entitle...,Had your mobile 11 months or more U R entitled...,"[Had, your, mobile, 11, months, or, more, U, R...","[Had, mobile, 11, months, U, R, entitled, Upda...","[had, mobil, 11, month, u, r, entitl, updat, l...","[Had, mobile, 11, month, U, R, entitled, Updat..."
8,ham,I'm gonna be home soon and i don't want to tal...,Im gonna be home soon and i dont want to talk ...,"[Im, gonna, be, home, soon, and, i, dont, want...","[Im, gonna, home, soon, dont, want, talk, stuf...","[im, gonna, home, soon, dont, want, talk, stuf...","[Im, gonna, home, soon, dont, want, talk, stuf..."
9,spam,"SIX chances to win CASH! From 100 to 20,000 po...",SIX chances to win CASH From 100 to 20000 poun...,"[SIX, chances, to, win, CASH, From, 100, to, 2...","[SIX, chances, win, CASH, From, 100, 20000, po...","[six, chanc, win, cash, from, 100, 20000, poun...","[SIX, chance, win, CASH, From, 100, 20000, pou..."

In [38]:
def clean_text(text):
    text = "".join([char for char in text if char not in string.punctuation])
    tokens = re.split('\W+', text)
    text = [ps.stem(word) for word in tokens if word not in stopwords]
    return text

In [39]:
from sklearn.feature_extraction.text import CountVectorizer
count_vect = CountVectorizer(analyzer = clean_text)
x_counts = count_vect.fit_transform(data['body_text'])
print(x_counts.shape)
print(x_counts.toarray())

(5568, 8191)
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]

In [18]:
x_counts

<5568x8191 sparse matrix of type '<class 'numpy.int64'>'
	with 55626 stored elements in Compressed Sparse Row format>

In [19]:
x_counts_df = pd.DataFrame(x_counts.toarray(),
                            columns = count_vect.get_feature_names())
x_counts_df.head()

,,0,008704050406,0089mi,0121,01223585236,01223585334,0125698789,02,020603,...,zindgi,zoe,zogtoriu,zoom,zouk,zyada,é,ü,üll,〨ud
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

data = pd.read_csv("C:\\Users\\PC\\Desktop\\Cours_INGC3\\NLP\\SMSSpamCollection.tsv", sep ="\t",
                  names = ['label', 'body_text'], header = None)
data.head()
from sklearn.feature_extraction.text import CountVectorizer
count_vect = CountVectorizer(ngram_range = (3,3))
x_counts = count_vect.fit_transform(data['body_text'])
print(x_counts.shape)
print(x_counts.toarray())

In [21]:
x_counts_df = pd.DataFrame(x_counts.toarray(),
                            columns = count_vect.get_feature_names())
x_counts_df.head()

,00 in our,00 sub 16,00 subs 16,000 bonus caller,000 cash await,000 cash needs,000 cash or,000 homeowners tenants,000 pounds txt,000 price to,...,zhong se qing,zindgi wo hai,zindgi wo nahi,zoe 18 to,zoe it just,zogtorius ve been,zoom to cine,zouk with nichols,zyada kisi ko,ú1 20 poboxox36504w45wq
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [22]:
from sklearn.feature_extraction.text import TfidfVectorizer
count_vect = CountVectorizer(analyzer = clean_text)
x_tfidf = count_vect.fit_transform(data['body_text'])
print(x_tfidf.shape)
print(x_tfidf.toarray())

(5568, 8191)
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]

In [23]:
x_tfidf_df = pd.DataFrame(x_tfidf.toarray(),
                            columns = count_vect.get_feature_names())
x_tfidf_df.head()

,,0,008704050406,0089mi,0121,01223585236,01223585334,0125698789,02,020603,...,zindgi,zoe,zogtoriu,zoom,zouk,zyada,é,ü,üll,〨ud
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0